apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dftp

resources:
  - namespace-and-secrets.yaml
  - transaction-service-deployment.yaml
  - account-service-deployment.yaml
  - ledger-service-deployment.yaml
  - hpa-transaction-service.yaml

commonLabels:
  app.kubernetes.io/part-of: distributed-financial-transaction-platform
  app.kubernetes.io/managed-by: kustomize
