apiVersion: v1
kind: Namespace
metadata:
  name: dftp
  labels:
    name: dftp
    environment: production
    app.kubernetes.io/part-of: distributed-financial-transaction-platform

---
apiVersion: v1
kind: Secret
metadata:
  name: dftp-db-credentials
  namespace: dftp
  labels:
    app.kubernetes.io/part-of: distributed-financial-transaction-platform
type: Opaque
stringData:
  POSTGRES_USER: "dftp_app_user"
  POSTGRES_PASSWORD: "CHANGE_ME_IN_VAULT_PROD_PASSWORD"
  TRANSACTION_DB_URL: "jdbc:postgresql://postgres-cluster.dftp.svc.cluster.local:5432/transaction_db?sslmode=verify-full&sslrootcert=/etc/ssl/certs/pg-root.crt"
  ACCOUNT_DB_URL: "jdbc:postgresql://postgres-cluster.dftp.svc.cluster.local:5432/account_db?sslmode=verify-full&sslrootcert=/etc/ssl/certs/pg-root.crt"
  LEDGER_DB_URL: "jdbc:postgresql://postgres-cluster.dftp.svc.cluster.local:5432/ledger_db?sslmode=verify-full&sslrootcert=/etc/ssl/certs/pg-root.crt"

---
apiVersion: v1
kind: Secret
metadata:
  name: dftp-kafka-secrets
  namespace: dftp
  labels:
    app.kubernetes.io/part-of: distributed-financial-transaction-platform
type: Opaque
stringData:
  KAFKA_BOOTSTRAP_SERVERS: "kafka-bootstrap.kafka.svc.cluster.local:9092"
  KAFKA_SECURITY_PROTOCOL: "SASL_SSL"
  KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
  KAFKA_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"dftp-service\" password=\"CHANGE_ME_KAFKA_SCRAM_SECRET\";"

---
apiVersion: v1
kind: Secret
metadata:
  name: dftp-jwt-secrets
  namespace: dftp
  labels:
    app.kubernetes.io/part-of: distributed-financial-transaction-platform
type: Opaque
stringData:
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyY0/example...
    -----END PUBLIC KEY-----
  JWT_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEowIBAAKCAQEAyY0/example...
    -----END RSA PRIVATE KEY-----
  INTERNAL_API_SECRET: "DFTP-INTERNAL-RECONCILIATION-SECRET-KEY-PROD"
